const VALOR_CARTELA = 2.5;

const FUNDO_PREMIO_BRUTO = 2.0;

module.exports = Object.freeze({

  VALOR_CARTELA,

  FUNDO_PREMIO_BRUTO,

  DESPESAS_OPERACIONAIS: 0.25,
  VALOR_INDICACAO: 0.25,

  // Percentuais calculados
  PERCENTUAL_PREMIO: FUNDO_PREMIO_BRUTO / VALOR_CARTELA,
  PERCENTUAL_INDICACAO: 0.25 / VALOR_CARTELA,
  PERCENTUAL_DESPESA: 0.25 / VALOR_CARTELA,

});